project:
  type: website
  output-dir: docs

website:
  navbar:
  #favicon: <insert png file from folder here from fontawesome>
    title: false
    #logo: <insert images png here>
    #logo-alt: <insert alt text here since its an image>
    left:
        - href: index.qmd
          text: Home
        - about.qmd
        - Blog.qmd
        - href: resources.qmd
          text: Resources
        - href: LianeChenResume.pdf
        - text: CV
  page-footer: 
    background: light
    left: 
      - "Copyright 2021, Liane Chen"
    right: 
      - icon: github
      # - href: http://github.com/lchenhub (check link and update)

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true

editor: visual

