{
  "hash": "f4c4d12de5abf4d0fd8c3b804f27ba30",
  "result": {
    "markdown": "---\ntitle: \"Impact of Poverty on a City's Overall Readiness for Climate Adaptation\"\nauthor: \n  - name: Liane Chen\n    url: https://lchenhub.github.io/\n    affiliation: MEDS (UCSB) \n    affiliation-url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science\ndate: 12-15-2023\ncategories: [MEDS, Statistics, Poverty, Climate Adaptation, R]\ncitation:\n    url: https://lchenhub.github.io/blog/2023-12-15-Poverty-and-Climate-Readiness/\nimage: images/poverty_climate.jpg\n---\n\n\n# Introduction\n\nThis blog post will explore analysis conducted on whether poverty impacts a city's overall readiness to implement climate adaptation measures at both national and regional levels in the United States.\n\n## Research Question\n\nWhat impact does the percentage of population in poverty have on a city's overall readiness score for climate adaptation?\n\n### Motivation\n\nClimate change is upon us. The task of addressing its intensifying effects is daunting and more urgent than ever. We need to adapt to climate change now, which means taking action to adjust to its present and future impacts (EU 2023).\n\nAdaptation and resilience refers to adjustments in ecological, social or economic systems in response to actual or expected climatic stimuli and their effects. At the global stage, we have seen governments iterate the importance of climate adaptation and resilience. Adopted in 2015 and signed in 2016, the Paris Agreement is a legally binding international treaty on climate change. All Parties to the Paris Agreement committed to strengthening the global response to climate change by increasing the ability of all to adapt and build resilience, and reduce vulnerability. In order to do so, governments will need access to clear and accurate data as they move to prepare our economies and communities as a whole. It is important to consider the effects of adaptation on less resourced communities, as poor populations tend to be the most vulnerable to climate change and least able to adapt because of limited capacity to cope with climate variability and extremes. For example, many socially vulnerable groups (i.e., low-income households, communities of color, the unhoused, and immigrant populations) live in urban areas that are prone to extreme heat (urban heat islands). Some may also live in housing that does have adequate insulation or cooling. Others may not be able to afford air conditioning. It should be noted that this is just one aspect of social vulnerability and overlaps may occur.\n\nThis analysis will provide exploratory analysis on whether poverty is a factor in how ready a city is for climate change. A total of 278 cities within the United States, including 50 states and Puerto Rico, whose populations are above 100,000 people will be examined.\n\n### Data\n\nClimate adaptation readiness (hereon referred to as 'climate readiness') and poverty data used for this analysis is publicly available from the Notre Dame Global Adaptation Initiative through its Urban Adaptation Assessment. The data is available in CSV format, with nine independent files that reflect data used to generate each of the hazard scores and forecasts and the primary data at the city level and sub-city level (census tract). Each file has a common city, state and geographic identifiers (GEOIDs) variable that permits easy identification and merging, if necessary. The City Indicators.csv and Overall Risk & Readiness Scores.csv files were both used for the analysis.\n\n## Data Analysis\n\nI started with basic analysis to explore the data. Luckily, the two data files have common geospatial and temporal features that allowed for easy manipulation and use. Minor cleaning was required to correct inaccurate spelling and to ensure uniform formatting in column names. Once I checked that both data files had matching cities and number of observations, I combined the datasets based on city names to create a merged dataframe which includes percentage of population in poverty and overall climate adaptation readiness. I also removed certain columns to make the merged dataframe easier to work with.\n\nNext, I chose to conduct a simple linear regression model as the two variables I am studying are numeric values. I used 'ggplot' to create a scatter plot comparing the percent of population in poverty to the climate readiness score for each city. Then I used 'geom_smooth()' to plot the linear regression between poverty and climate readiness. As a basic gut check, the line shows that there is a negative correlation between the two variables, which makes sense as higher poverty would decrease ability to implement costly climate adaptation measures.\n\nI also conducted a two-tailed t-test to see whether there was a difference in the impact of poverty on climate readiness between two regions (West and South).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\n\n# load all the packages needed \nlibrary(tidyverse)\nlibrary(readr)\nlibrary(gt)\nlibrary(tufte)\nlibrary(sf)\nlibrary(feasts)\nlibrary(dplyr)\nlibrary(janitor)\nlibrary(ggplot2)\n\n# set the filepath  \nrootdir <- (\"/Users/lianechen/Documents/MEDS_2023/Fall_2023/EDS222/Final/eds222-climateadapt\")\n\ndatadir <- file.path(rootdir,\"data\")\n\n# import data\ncity_indicators <- read.csv(\"data/City Indicators.csv\")\nreadiness <- read.csv(\"data/Overall Risk & Readiness Scores.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# clean column names for both datasets\ncity_indicators <- clean_names(city_indicators)\nreadiness <- clean_names(readiness)\n\n# check number of observations for city_indicators file\nnrow(city_indicators)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 278\n```\n:::\n\n```{.r .cell-code}\n# check number of observations for readiness file\nnrow(readiness)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 278\n```\n:::\n\n```{.r .cell-code}\n# merge city_indicators and readiness files by city name\nmerged <- merge(city_indicators, readiness, by = \"city\", all = TRUE)\n\n# check that number of obersvations is consistent\nnrow(merged)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 278\n```\n:::\n\n```{.r .cell-code}\n# clean column names\ncolnames(merged)[colnames(merged) == \"geo_id.x\"] <- \"geo_id\"\ncolnames(merged)[colnames(merged) == \"state.x\"] <- \"state\"\ncolnames(merged)[colnames(merged) == \"latitutde\"] <- \"latitude\"\n\n# streamline the columns so only relevant ones are kept\nincome_readiness <- merged[, c(\"city\", \"state\", \"geo_id\", \"percent_of_population_spending_over_50_percent_of_income_on_rent_2015\", \"percent_of_population_in_poverty_2015\", \"latitude\", \"longitude\", \"county\", \"region\", \"median_income\", \"overall_readiness\")]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# create scatter plot with simple regression line included\nggplot(data=income_readiness, aes(x=percent_of_population_in_poverty_2015, y = overall_readiness)) + \n  geom_point(alpha=0.1, size=3) + \n  geom_smooth(method='lm', formula= y~x, color=\"lightcoral\", se=F, linewidth=1.5) +\n  theme_bw() +\n  labs(title = \"Scatterplot of % in Poverty vs Overall Readiness with Regression Line\",\n       x = \"Percent of population in poverty (2015)\", y = \"Overall readiness\")\n```\n\n::: {.cell-output-display}\n![](climateadapt_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe slope of the regression line shows to be slightly negative, as y decreases while x increases. This seems to make intuitive sense, as increased poverty could relate to decreased ability to adapt to climate variability and extremes.\n\nThe slope is not too steep, so let's take a look at correlation to see how strongly poverty impacts climate adaptation readiness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute the correlation coefficient to quantify the strength and direction of the relationship between poverty and climate readiness\n\ncor(income_readiness$percent_of_population_in_poverty_2015, income_readiness$overall_readiness)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.1565957\n```\n:::\n:::\n\n\nMagnitude of the Correlation Coefficient:\n\nThe correlation coefficient ranges from -1 to 1. A value of -1 indicates a perfect negative correlation, 0 indicates no correlation, and 1 indicates a perfect positive correlation.\n\nIn this case, the value is very close to 0, which suggests a weak correlation.\n\nSign of the Correlation Coefficient:\n\nThe negative sign indicates a negative correlation. A negative correlation means that as one variable (percentage in poverty) increases, the other variable (overall adaptation readiness) tends to decrease.\n\nThis matches the slight negative slope of the regression line.\n\nInterpretation:\n\nWith a correlation coefficient of -0.1565957, there is a slight tendency that areas with a higher percentage of people in poverty may have lower overall adaptation readiness. However, the correlation is weak, suggesting that other factors not considered in this analysis may play a more significant role in determining overall adaptation readiness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# linear regression model\nlinear_regression <- lm(overall_readiness ~ percent_of_population_in_poverty_2015, data = income_readiness)\n\n# summary of the model\nsummary(linear_regression)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = overall_readiness ~ percent_of_population_in_poverty_2015, \n    data = income_readiness)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.30807 -0.08339 -0.00655  0.07662  0.35538 \n\nCoefficients:\n                                        Estimate Std. Error t value Pr(>|t|)\n(Intercept)                            0.5098146  0.0163942  31.097  < 2e-16\npercent_of_population_in_poverty_2015 -0.0023953  0.0009093  -2.634  0.00891\n                                         \n(Intercept)                           ***\npercent_of_population_in_poverty_2015 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.124 on 276 degrees of freedom\nMultiple R-squared:  0.02452,\tAdjusted R-squared:  0.02099 \nF-statistic: 6.938 on 1 and 276 DF,  p-value: 0.008913\n```\n:::\n:::\n\n\nIntercept (0.5098146):\n\nThe intercept represents the estimated value of the dependent variable when all independent variables are zero.\n\nIn this context, when the percentage of the population in poverty is zero, the estimated value of overall adaptation readiness is approximately 0.5098.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# let's look at coefficients\nsummary(linear_regression)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                          Estimate   Std. Error   t value\n(Intercept)                            0.509814590 0.0163942390 31.097179\npercent_of_population_in_poverty_2015 -0.002395259 0.0009093408 -2.634061\n                                          Pr(>|t|)\n(Intercept)                           3.482886e-92\npercent_of_population_in_poverty_2015 8.913263e-03\n```\n:::\n:::\n\n\nPercentage of Population in Poverty Coefficient (-0.0023953):\n\nThe coefficient for the variable \"percent_of_population_in_poverty_2015\" represents the estimated change in the dependent variable (overall adaptation readiness) for a one-unit change (one-percent) in the independent variable (percentage of population in poverty).\n\nIn this case, for every one-unit increase in the percentage of the population in poverty, the overall adaptation readiness is estimated to decrease by approximately 0.0024.\n\nThe t-value of -2.634 indicates that this coefficient is statistically significant (p = 0.00891), suggesting that the percentage of the population in poverty has a significant effect on overall adaptation readiness.\n\nIn summary, the model suggests that both the intercept and the percentage of the population in poverty are statistically significant in predicting overall adaptation readiness.\n\n## Two-Tailed T-Testing\n\nI am curious whether there is a difference between how poverty impacts climate readiness in different regions of the country. Let's conduct a two-tailed t-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute point estimate\npt_est_poverty_west = income_readiness %>% \n  filter(region == \"West\") %>% \n  summarize(mean(percent_of_population_in_poverty_2015))\n\npt_est_poverty_south = income_readiness %>% \n  filter(region == \"South\") %>% \n  summarize(mean(percent_of_population_in_poverty_2015))\n\npoint_est = as.numeric(pt_est_poverty_west - pt_est_poverty_south)\nprint(point_est) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3.538473\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute standard error\nn1 = income_readiness %>% filter(region == \"West\") %>% count()\nn2 = income_readiness %>% filter(region == \"South\") %>% count()\ns1 = income_readiness %>% filter(region == \"West\") %>% summarize(sd(percent_of_population_in_poverty_2015, na.rm = TRUE))\ns2 = income_readiness %>% filter(region == \"South\") %>% summarize(sd(percent_of_population_in_poverty_2015, na.rm = TRUE))\n\nSE = as.numeric(sqrt(s1^2/n1 + s2^2/n2))\nprint(SE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.18189\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute test statistic\nzscore = (point_est - 0)/SE\nprint(zscore)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2.99391\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#construct two-tailed t-test\ntwo_tailed <- t.test(income_readiness$overall_readiness[income_readiness$region==\"West\"], income_readiness$overall_readiness[income_readiness$region==\"South\"])\n\n#print\ntwo_tailed\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  income_readiness$overall_readiness[income_readiness$region == \"West\"] and income_readiness$overall_readiness[income_readiness$region == \"South\"]\nt = -2.4308, df = 92.995, p-value = 0.01698\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -0.11160120 -0.01124421\nsample estimates:\nmean of x mean of y \n0.3952240 0.4566467 \n```\n:::\n:::\n\n\nInterpreting P-value and Hypothesis Testing for Different Regions (West and South) p-value: 0.01698\n\nNull: The mean score for overall climate readiness in the West region is equal to the mean score for overall climate readiness in the South region when considering the impact of poverty (no difference). H_0: u_WestReadiness - u_SouthReadiness = 0\n\nAlternative: The mean score for overall climate readiness in the West region is NOT equal to the mean score for overall climate readiness in the South region when considering the impact of poverty (yes, there is a difference). H_A: u_WestReadiness - u_SouthReadiness != 0\n\nGiven that the p-value is less than the significance level of 'alpha=0.05', we reject the null hypothesis. Therefore, we can say that there is a difference in mean overall climate readiness between the West and the South when considering the impact of poverty.\n\n## Results\n\nWe are able to reject the null hypothesis and conclude that the percentage of people living in poverty does indeed have an impact on a city's climate readiness score. It should be noted that while there is a correlation, it is relatively weak, which suggests that further analysis should be completed.\n\n## Future Work\n\nCorrelation does not imply causation. Even though we found above that there is a correlation, it doesn't necessarily mean that poverty causes lower adaptation readiness or vice versa. Other factors might contribute to the observed relationship. Future work should explore additional variables and regression analysis to better understand the specific nature and strength of the relationship, with controls included. Further assess the statistical significance of the correlation coefficient to determine whether the observed relationship is likely due to chance.\n\nIn summary, the negative correlation coefficient suggests a weak tendency for areas with a higher percentage of people in poverty to have lower overall adaptation readiness. The strength of this relationship is not strong, and it's important to interpret such correlations cautiously, considering other factors that might influence the observed pattern. Potential areas for further work are described below.\n\n### More Cities Data\n\nThe datasets used included 278 cities within the United States, including 50 states and Puerto Rico, whose populations are above 100,000 people. However, increased data for cities with population under 100,000 would provide a broader understanding of potential opportunity areas for climate adaptation.\n\n### Additional Years of Poverty Data\n\nThis analysis would benefit from additional years of data for percentage of populations living in poverty from the Census. While these numbers would likely not vary too dramatically between years, it would provide more accurate data.\n\n### Wealth Data\n\nWe have available data for percentage of populations living in poverty, but what about wealthy populations? It would be helpful (and interesting!) to be able to statistically compare whether wealth has an impact on climate readiness.\n\n## Code Availability\n\nhttps://github.com/lchenhub/eds222-climate-adaptation.git\n\n## References\n\n### Data\n\n1.  University of Notre Dame, Global Adaptation Initiative: https://gain-uaa.nd.edu/\n\n### Literature Cited\n\n1.  European Union(EU) 2003. European Commission, Adaptation to climate change. https://climate.ec.europa.eu/eu-action/adaptation-climate-change_en\n\n2.  United Nations 2023a. Climate Adaptation. https://www.un.org/en/climatechange/climate-adaptation\n\n3.  United Nations 2023b. New elements and dimensions of adaptation under the Paris Agreement (Article 7). https://unfccc.int/topics/adaptation-and-resilience/the-big-picture/new-elements-and-dimensions-of-adaptation-under-the-paris-agreement-article-7\n\n4.  United Stated Environmental Protection Agency 2023. Climate Change and the Health of Socially Vulnerable People. Last updated October 16, 2023. https://www.epa.gov/climateimpacts/climate-change-and-health-socially-vulnerable-people#:\\~:text=Increases%20in%20average%20and%20extreme,including%20certain%20socially%20vulnerable%20groups.&text=These%20include%20low%2Dincome%20households,experiencing%20homelessness%2C%20and%20immigrant%20populations\n",
    "supporting": [
      "climateadapt_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}